// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmoxjkzjwfbuatjxsbsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdtb3hqa3pqd2ZidWF0anhzYnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTY1MDAsImV4cCI6MjA3NTE3MjUwMH0.Iv8zlymLSSSnrdrR2Nn0AyggsGvJ9lPI46tU_3LxYG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});